### ISSUE TITLE
Set up CI/CD

### ISSUE THREAD

**Issue by joacar** [CureMedia/Localization#6]
- [x] AppVeyor
- [x] Cake
- [ ] GitVersioning
- [x] Deploy NuGet
- [x] Release

# AppVeyor
`appveyor.yml` seem to be doing it right.

# Cake
Initial script works fine.

# Versioning
How to version properly without to much manual steps.

From [AppVeyor](https://www.appveyor.com/docs/build-configuration/)
```
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
```

# Deploy NuGet
Publish to **MyGet** when `master` is built and _should_ publish to `NuGet.org` on release tag creation.

# Release
[AppVeyor](https://www.appveyor.com/docs/deployment/github/)
```
deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: <your encrypted token> # your encrypted token from GitHub
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
```
